version: '3'
services:
  api:
    container_name: api
    build:
      context: './api'
    volumes:
      - './api:/app'
    ports:
      - '8000:8000'
    depends_on:
      - rabbitmq
  
  rabbitmq:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    container_name: celery
    command: celery -A hunter worker -l INFO
    build:
      context: './api'
    volumes:
      - './api:/app'
    depends_on:
      - api
      - rabbitmq
